name: Verible Check Linter

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - master

jobs:
  verible:
    runs-on: ubuntu-latest

    # Use prebuilt container
    container:
      image: ghcr.io/yangyt96/verible:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Verible Linter
        # continue-on-error: true
        run: |
          SV_FILES="$(find ./ -type f \( -path "*/sim/*.sv" \))"
          verible-verilog-lint \
          --rules_config_search \
            ${SV_FILES}
      - name: Check Formatting
        # continue-on-error: true
        run: |
          SV_FILES="$(find ./ -type f \( -path "*/sim/*.sv" -o -name "axi4_stream_dut.sv" \))"
          verible-verilog-format \
          --verify --inplace \
            ${SV_FILES}
