name: VUnit Test

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - master

jobs:
  vunit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run VUnit inside container
        uses: addnab/docker-run-action@v3
        with:
          image: docker.io/filippobrogi/modelsim
          options: -v ${{ github.workspace }}:/workspace
          run: |
            cd /workspace
            find / -type f -name vsim -print -quit 2>/dev/null
            export PATH="/opt/intelFPGA/modelsim_ase/linuxaloem/:${PATH}"
            export PATH="/opt/intelFPGA/modelsim_ase/bin/:${PATH}"
            echo $PATH
            /opt/intelFPGA/modelsim_ase/linuxaloem/vsim -version
            # export VUNIT_MODELSIM_PATH=/opt/intelFPGA/modelsim_ase/linuxaloem/vsim
            # echo $VUNIT_MODELSIM_PATH
            pip3 install vunit_hdl
            find . -name "run.py" -print0 | xargs -0 -n1 python3
